### ISSUE TITLE
Tag 5.1.0 not found in repository docker.io/nodesource/trusty

### ISSUE THREAD

**Issue by matthewoden** [nodesource/docker-node#45]
Seems that the nodesource/trusty docker repo got dropped from hub.docker.com within the last hour or so?

**Comment by cymen** [comment]
I'm seeing the same thing for `nodesource/trusty:4.2.4` and `nodesource/trusty:4.2.3`.

**Comment by retrohacker** [comment]
@cymen @matthewoden Yes.

We are in the process of migrating off of the automated builds: https://nodesource.com/blog/nodesources-docker-images/

In order to convert an image from an automated build to a regular repository, Docker Hub requires that you first delete the repository and recreate it.

We had anticipated there to be about a 10 minute disruption in availability while we uploaded the images to the docker registry: https://twitter.com/NodeSource/status/693114472366366720 . This estimate was based on a test run I had done several weeks ago in preparation for today. This was done on a test account on the Docker Hub.

We are about 1 hour and 10 minutes into the transfer now and only Jessie has uploaded. I fear that our uploads are being throttled at some layer, and (based on the 5XX errors I'm ocassionally seeing during the upload) we may be being rate limited as well. I wouldn't be surprised by this, we did just delete several hundred docker images and are now pushing ~300GB worth of images to their servers.

An additional complication arose during the process of deleting the repositories and recreating them. It appears that Docker Hub has gotten itself into an unstable state. The repository is deleted, as you can see. However the hub is preventing me from recreating it, giving an error message saying that the repository already exists.

I've reached out to the Docker's support team for both of these issues and will be posting updates here as they become available.

**Comment by cymen** [comment]
@retrohacker :+1: thank you -- I appreciate the work you and the rest of the team do.

**Comment by retrohacker** [comment]
In the meantime, the images can be built directly on your machine by doing the following:

```
git clone https://github.com/nodesource/docker-node.git
cd docker-node/base/ubuntu/trusty
docker build -t nodesource/trusty-base .
cd ../../../ubuntu/trusty/node/4.2.4
docker build -t nodesource/trusty:4.2.4
```

**Comment by retrohacker** [comment]
@cymen :heart:

**Comment by retrohacker** [comment]
@cymen and @matthewoden,

Docker support came through and was able to get the trusty repository back up. I triggered a second push last night before going to bed and it filled in the holes caused by the 500s as well as populated the new trusty repo.

We are back to 100% coverage, thank you for your patience while we performed the migration.

https://hub.docker.com/r/nodesource/trusty/tags/
